/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistsRouteImport } from './routes/watchlists'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as AgendasRouteImport } from './routes/agendas'
import { Route as IndexRouteImport } from './routes/index'

const WatchlistsRoute = WatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendasRoute = AgendasRouteImport.update({
  id: '/agendas',
  path: '/agendas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendas': typeof AgendasRoute
  '/developers': typeof DevelopersRoute
  '/feed': typeof FeedRoute
  '/pipeline': typeof PipelineRoute
  '/search': typeof SearchRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendas': typeof AgendasRoute
  '/developers': typeof DevelopersRoute
  '/feed': typeof FeedRoute
  '/pipeline': typeof PipelineRoute
  '/search': typeof SearchRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendas': typeof AgendasRoute
  '/developers': typeof DevelopersRoute
  '/feed': typeof FeedRoute
  '/pipeline': typeof PipelineRoute
  '/search': typeof SearchRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendas'
    | '/developers'
    | '/feed'
    | '/pipeline'
    | '/search'
    | '/watchlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendas'
    | '/developers'
    | '/feed'
    | '/pipeline'
    | '/search'
    | '/watchlists'
  id:
    | '__root__'
    | '/'
    | '/agendas'
    | '/developers'
    | '/feed'
    | '/pipeline'
    | '/search'
    | '/watchlists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendasRoute: typeof AgendasRoute
  DevelopersRoute: typeof DevelopersRoute
  FeedRoute: typeof FeedRoute
  PipelineRoute: typeof PipelineRoute
  SearchRoute: typeof SearchRoute
  WatchlistsRoute: typeof WatchlistsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlists': {
      id: '/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof WatchlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendas': {
      id: '/agendas'
      path: '/agendas'
      fullPath: '/agendas'
      preLoaderRoute: typeof AgendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendasRoute: AgendasRoute,
  DevelopersRoute: DevelopersRoute,
  FeedRoute: FeedRoute,
  PipelineRoute: PipelineRoute,
  SearchRoute: SearchRoute,
  WatchlistsRoute: WatchlistsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
